// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udipxsrlssydvdenvmfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkaXB4c3Jsc3N5ZHZkZW52bWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjMzMzcsImV4cCI6MjA2NTkzOTMzN30.hMaDRllqcUNtAUalk2Zt_S45uSzgi30_X9DVCM0T1M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);